#!/bin/sh

# Fuzzy find a file from $HOME, move to that file directory,
# and then opens it on $EDITOR.

# notes: keep in mind that if you want to cd automatically
# to the file you need to source the script. I will just
# recommend to create an alias/keybind

file="$(fd -tf -tl -H --exclude .git . ~ | fzf -i +m --black)"
[ -n "$file" ] && cd "$(dirname "$file")" && $EDITOR "$file" || return 1
