#!/bin/sh

# Git wrapper to handle both my git repos, and my dotfiles repo.

# todo: git commands autocomplete.

stderr_git_output_path="$XDG_RUNTIME_DIR/git_wrapper"
git "$@" 2> "$stderr_git_output_path"
stderr_git_output="$(cat "$stderr_git_output_path")"

if [ "${stderr_git_output#*ot a git repository}" != "$stderr_git_output" ]; then
    echo "Not a git repository... perfoming action on dotfiles." # todo: Export to disable the echo 
    dotfiles "$@"
else
    [ -n "$stderr_git_output" ] && echo "$stderr_git_output"
fi
