#!/bin/bash

# Cd `up` an x amount of folders

# NOTE: keep in mind that if you want to see the effect of cd you need to source the file.

Amount=${1:-1}

if ((Amount <= 0)); then
    # shellcheck disable=2086
    printf "You can't cd up %s times\n" $Amount 1>&2
    return 1
fi

for ((I = 1; I <= Amount; I++)); do
    Level+=../
done

cd $Level || return 1

unset Amount
unset Level
