#!/bin/bash

# Fuzzy find a directory, then cd to it.

# Notes:
# Keep in mind that if you want to see the effect of cd you need to
# source the script.

# Dependecies:
# fd
# fzf
# realpath

# -------------------------------- Functions -------------------------------- #

Usage()
{
    while read -r; do
        printf "%s\n" "$REPLY"
    done <<- EOF
        Usage: gd [OPTS] [BASEDIR]

          -h, --help     - Display this help information.
          -a, --absolute - Prints the absolute path of the directory.
          -r, --relative - Prints the relative path of the directory.

        If called without arguments, BASEDIR will be the user's 'HOME'.
        If '-a' and '-r' are both being used, the program will use the last set.
	EOF
}

UnsetVars()
{
    unset Command
    unset BaseDir
}

Err()
{
    printf "Err: %s\n" "$2" 1>&2
    if (($1 > 0)); then
        UnsetVars
        return $1
    fi
}

# ----------------------------- Input Processing ----------------------------- #

(($# > 3)) && return $(Err 1 "Too many arguments.")

Command="cd"

while [[ -n $1 ]]; do
    case $1 in
        --help | -h)
            Usage
            return 0
            ;;
        --absolute | -a) Command="realpath" ;;
        --relative | -r) Command="echo" ;;
        -*) return $(Err 1 "Incorrect option(s) specified.") ;;
        *) break ;;
    esac
    shift
done

BaseDir="${1:-$HOME}"

[[ -d $BaseDir ]] || return $(Err 1 "Directory '$BaseDir' doesn't exists.")

# ----------------------------------- Main ----------------------------------- #

$Command "$(fd -td -H --exclude .git . "$BaseDir" | fzf -i +m --black)"

UnsetVars
