#!/bin/bash

# I refuse to make `pyenv` sourcable, so source this file to actually activate
# the virtual environment. This takes the exactly same parameters that pyenv
# does. You can alias this script to `pyenv` safetely.

PyEnvOut=$(\pyenv "$@"); read -r <<< "$?"

if (( REPLY == 0 )); then
    echo "$PyEnvOut"
elif (( REPLY == 3 )); then
    # shellcheck disable=1090
    . "$PyEnvOut"
fi

unset PyEnvOut
