#!/bin/bash

# Fuzzy Find the File system.

# -------------------------------- Functions -------------------------------- #

Err()
{
    printf "Err: %s\n" "$2" 1>&2
    # shellcheck disable=2086
    (($1 > 0)) && exit $1
}

# ----------------------------- Input Processing ----------------------------- #

while [[ -n $1 ]]; do
    case $1 in
        --)
            shift
            break
            ;;
        -*) Err 1 "Incorrect option(s) specified." ;;
        *) WorkingDir=$1 ;;
    esac
    shift
done

if [[ -z $WorkingDir ]]; then
    WorkingDir=$PWD
fi

[[ -d $WorkingDir ]] || Err 1 "Directory '$WorkingDir' doesn't exists."

# ----------------------------------- Main ----------------------------------- #

realpath "$(fd -HI -E .git -E .venv "$@" . "$WorkingDir" | fzf -i -m --black --history="$XDG_DATA_HOME/fzf/history" --history-size=10000)" 2> /dev/null

# FIX: How I can select multiple files that contain spaces?
#
# If I'm selecting multiple files ( no spaces ), I can use `3f ~` ( no quotes ).
# If I'm selecting a single file ( with spaces ), I can use "`3f ~`".
#
# However, I don't think I can do the same with multiple files with spaces. So
# the only solution would be to use `rfsn` on those files.
#
# readarray -t Output <<< "$(realpath "${FzfOutput[@]}")"
#
# echo "${Output[@]}"

