#!/bin/bash

# Fuzzy find a file, cd to that file directory, and then opens it on $EDITOR.

# NOTE: Keep in mind that if you want to cd automatically to the file you need
# to source the script. I will just recommend to create an alias/keybind.

# FIX: Doesn't work if multiple files are selected.
# TODO: Flag to force to open on $EDITOR.

_GO_TO_FILE()
{
    cd "${1%/*}" || return 1

    local File=${1##*/}

    if [[ -n $IMAGE ]]; then
        if file "$File" | grep -qE "image|bitmap"; then
            $IMAGE "$File"
        fi
    else
        $EDITOR "$File"
    fi
}

if [[ $1 == "-" ]]; then
    if [[ -n $_GF_FILE ]]; then
        _GO_TO_FILE "$_GF_FILE"
    else
        echo "No previous file visited."
    fi
    return 1
fi

_GF_FILE=$(3f "${1:-$HOME}" -- -tf -tl)
[[ -f $_GF_FILE ]] && _GO_TO_FILE "$_GF_FILE"
